test: crhelper.c testcresearcher.c boxscorebuffer.c
	gcc crhelper.c testcresearcher.c boxscorebuffer.c -I /Users/faiyamrahman/\
	programming/Python/beatthestreak/beatthestreak/CExtensions/CResearcher/uthash-master/src -o test
python:
	python setup.py build
	python setup.py install